name: astro_partner_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+5

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  agora_rtc_engine: ^6.5.3
  audioplayers: ^6.5.1
  cached_network_image: ^3.4.1
  carousel_slider: ^5.1.1
  cloud_firestore: ^6.0.3
  crypto: ^3.0.6
  dio: ^5.9.0
  dots_indicator: ^4.0.1
  file_picker: ^10.3.3
  flutter_rating_bar: ^4.0.1
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.2.1
  fluttertoast: ^9.0.0
  get: ^4.7.2
  http: ^1.5.0
  image_picker: ^1.2.0
  intl: ^0.20.2
  intl_phone_field: ^3.2.0
  otp_pin_field: ^1.4.1
  package_info_plus: ^9.0.0
  photo_view: ^0.15.0
  share_plus: ^12.0.1
  shimmer: ^3.0.0
  upgrader: ^12.1.0
  url_launcher: ^6.3.2
  uuid: ^4.5.1
  firebase_crashlytics: ^5.0.3
  firebase_messaging: ^16.0.3
  wakelock_plus: ^1.4.0
  permission_handler: ^12.0.1
  syncfusion_flutter_pdfviewer: ^31.2.3
  open_filex: ^4.7.0
  firebase_storage: ^13.0.3
  firebase_analytics: ^12.0.3
  firebase_core: ^4.2.0
  video_player: ^2.10.0
  flutter_local_notifications: ^19.5.0
  flutter_callkit_incoming: ^3.0.0

icons_launcher:
  image_path: "assets/images/lunch_icon.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true

dev_dependencies:
  icons_launcher: ^3.0.3
  change_app_package_name: ^1.2.0 #flutter pub run change_app_package_name:main vedam.roots.expert.app
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/


  fonts:
    - family: Product Sans
      fonts:
        - asset: fonts/ProductSans-Black.ttf
        - asset: fonts/ProductSans-BlackItalic.ttf
        - asset: fonts/ProductSans-Bold.ttf
        - asset: fonts/ProductSans-BoldItalic.ttf
        - asset: fonts/ProductSans-Italic.ttf
        - asset: fonts/ProductSans-Light.ttf
        - asset: fonts/ProductSans-LightItalic.ttf
        - asset: fonts/ProductSans-Medium.ttf
        - asset: fonts/ProductSans-MediumItalic.ttf
        - asset: fonts/ProductSans-Regular.ttf
        - asset: fonts/ProductSans-Thin.ttf
        - asset: fonts/ProductSans-ThinItalic.ttf
